services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: program
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: persons
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://program:test@postgres:5432/persons
    ports:
      - "8080:8080"

volumes:
  db-data: