name: Build, Test and Deploy

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: program
          POSTGRES_PASSWORD: test
          POSTGRES_DB: persons
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U program -d persons"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_HOST: localhost
      POSTGRES_USER: program
      POSTGRES_PASSWORD: test
      POSTGRES_DB: persons
      DATABASE_URL: postgresql+psycopg2://program:test@localhost:5432/persons

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres
        run: |
          python - <<'PY'
          import time, psycopg2
          for i in range(30):
              try:
                  conn = psycopg2.connect(
                      host="localhost", dbname="persons",
                      user="program", password="test"
                  )
                  conn.close()
                  print("Postgres is ready")
                  break
              except Exception as e:
                  print("Waiting for Postgres...", e)
                  time.sleep(1)
          else:
              raise RuntimeError("Postgres not available")
          PY

      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -v