name: Build, Test and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest -q
        # tests must pass to continue

      - name: Log in to GitHub Container Registry
        if: ${{ secrets.GITHUB_TOKEN != '' }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Docker image to GHCR
        if: ${{ secrets.GITHUB_TOKEN != '' }}
        run: |
          docker tag $IMAGE_NAME $IMAGE_NAME
          docker push $IMAGE_NAME

      - name: Trigger Render deploy (manual deploy of latest commit)
        if: ${{ secrets.RENDER_API_KEY && secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering deploy on Render for service $RENDER_SERVICE_ID"
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json" \
            -d '{}'